# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home of another front-end developer
email: spawnenius@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coffe and code, code and coffe - what else do you need?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://denissb.github.io" # the base hostname & protocol for your site
github_username:  denissb
facebook_username: deniss.borisov
linkedin_username: deniss-borisovs-5221b288
googleplus_username: +DenissBorisovs

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
