title: Deniss Borisovs | Web developer
description: Web developer focused on Front-end and UI/UX development
author:
  name: Deniss Borisovs,
  email: deniss.borisovs@gmail.com,
  url: https://denissb.github.io/
