name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/_config.ts', '**/import_map.json') }}

      - name: Build site
        run: |
          deno task build --location=https://denissb.github.io/
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
